### ISSUE TITLE
Electrify stopped working for my application

### ISSUE THREAD

**Issue by rIpteyed** [arboleya/electrify#17] opened 2015-10-09 16:17 UTC
I love this approach and I would like to use electrify to package our app.  I packaged our application last week at the beginning of the week and it worked well.  But, I took a break from this project until yesterday when I started fresh, added the electrify package and then ran Electrify.app.package() from the shell.  Everything seems to package fine, but now my app opens with a blank white page and won't load.  I'm getting a bunch of undefined errors starting with: Uncaught TypeError: Cannot read property 'Electrify' of undefined

<img width="540" alt="screen shot 2015-10-09 at 10 14 05 am" src="https://cloud.githubusercontent.com/assets/3117159/10399240/aa1d2392-6e6e-11e5-961d-f5572ddd7382.png">

As I reflect, the errors actually start as soon as I add the electrify package, even before I package the app.  Can you point me in the right direction?

Also note that your plugin works fine for me for simple apps like todos example and so on.

Thanks and awesome work, btw.
- Justin

**Comment by arboleya** [comment] 2015-10-09 23:34
Hi Justin, are you saying that everything works fine for a simple todo/leaderboard example, but not with bigger projects?

Please, start and package your project like this, then send me the full log you'll get on #tab1:

``` shell
# tab 1
cd /your/meteor/app/ && LOGELECTRIFY=ALL meteor

# tab2
cd /your/meteor/app/ && LOGELECTRIFY=ALL meteor shell
# then type Electrify.app.package()
```

Also tell me your version of Electrify, Meteor and Node (only if you are using electrify npm-package).

Thank you for the kind words.

**Comment by rIpteyed** [comment] 2015-10-09 23:37
Ok, I will try get this to you this weekend.  Thank you for responding.

B/r,

Justin

On Fri, Oct 9, 2015 at 5:34 PM, Anderson Arboleya notifications@github.com
wrote:

> Hi Justin, are you saying that everything works fine for a simple
> todo/leaderboard example, but not with bigger projects?
> 
> Please, start and package your project like this, then send me the full
> log you'll get on #tab1:
> 
> # tab 1cd /your/meteor/app/ && LOGELECTRIFY=ALL meteor
> 
> # tab2cd /your/meteor/app/ && LOGELECTRIFY=ALL meteor shell# then type Electrify.app.package()
> 
> Also tell me your version of Electrify, Meteor and Node (only if you are
> using electrify npm-package).
> 
> Thank you for the kind words.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arboleya/electrify/issues/17#issuecomment-147011295.

## 

Justin Rich
Owner, Rich Innovation, LLC
Salt Lake City, Utah
m 801 558 6964

**Comment by suchipi** [comment] 2015-10-19 05:18
I'm running into the same issue after first adding Electrify to my application (it didn't work prior). 
I see it in the Electron window that running `meteor` opens.
I'm using Meteor 1.1.0.3, Electrify 1.4.0, and Node v4.1.1 on Fedora 22 x64.
Relevant output (setting the environment variable is different because I use fish shell):

```
suchipi@Lilith ~/C/nutti (master) $ set -x LOGELECTRIFY ALL
suchipi@Lilith ~/C/nutti (master) $ meteor
[[[[[ ~/Code/nutti ]]]]]                      

=> Started proxy.                             
=> Meteor 1.2.0.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
I20151018-23:12:40.916(-6)? INFO  electrify:index:  initializing
I20151018-23:12:40.918(-6)? ====================================
I20151018-23:12:40.919(-6)? {
I20151018-23:12:40.919(-6)?   "version": "1.4.0",
I20151018-23:12:40.919(-6)?   "is_development_mode": false,
I20151018-23:12:40.919(-6)?   "is_running_tests": false,
I20151018-23:12:40.919(-6)?   "stdio": "inherit",
I20151018-23:12:40.919(-6)?   "sys": {
I20151018-23:12:40.919(-6)?     "platform": "linux",
I20151018-23:12:40.920(-6)?     "arch": "x64",
I20151018-23:12:40.920(-6)?     "is_windows": false,
I20151018-23:12:40.920(-6)?     "is_linux": true,
I20151018-23:12:40.920(-6)?     "is_osx": false
I20151018-23:12:40.920(-6)?   },
I20151018-23:12:40.920(-6)?   "os": {
I20151018-23:12:40.920(-6)?     "name": "linux",
I20151018-23:12:40.921(-6)?     "home": "/home/suchipi",
I20151018-23:12:40.921(-6)?     "tmp": "/tmp"
I20151018-23:12:40.921(-6)?   },
I20151018-23:12:40.921(-6)?   "app": {
I20151018-23:12:40.921(-6)?     "root": "/home/suchipi/Code/nutti",
I20151018-23:12:40.921(-6)?     "is_packaged": false,
I20151018-23:12:40.921(-6)?     "electrify": "/home/suchipi/Code/nutti/.electrify",
I20151018-23:12:40.921(-6)?     "bin": "/home/suchipi/Code/nutti/.electrify/bin",
I20151018-23:12:40.921(-6)?     "dist": "/home/suchipi/Code/nutti/.electrify/.dist",
I20151018-23:12:40.921(-6)?     "settings": {}
I20151018-23:12:40.922(-6)?   },
I20151018-23:12:40.922(-6)?   "core": {
I20151018-23:12:40.922(-6)?     "tmp": "/tmp/electrify",
I20151018-23:12:40.922(-6)?     "root": "/tmp/electrify/core",
I20151018-23:12:40.922(-6)?     "node_mods": "/tmp/electrify/core/node_modules",
I20151018-23:12:40.922(-6)?     "electron": "/tmp/electrify/core/node_modules/electron-prebuilt/cli.js",
I20151018-23:12:40.922(-6)?     "packager": "/tmp/electrify/core/node_modules/electron-packager/cli.js"
I20151018-23:12:40.923(-6)?   },
I20151018-23:12:40.923(-6)?   "meteor": {
I20151018-23:12:40.923(-6)?     "root": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/meteor",
I20151018-23:12:40.923(-6)?     "tools": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/",
I20151018-23:12:40.923(-6)?     "dev_bundle": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle",
I20151018-23:12:40.923(-6)?     "server_lib": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/server-lib",
I20151018-23:12:40.923(-6)?     "server_modules": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules",
I20151018-23:12:40.923(-6)?     "node_mods": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/lib/node_modules",
I20151018-23:12:40.923(-6)?     "node": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/bin/node",
I20151018-23:12:40.924(-6)?     "npm": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/bin/npm-cli.js",
I20151018-23:12:40.924(-6)?     "mongo": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongo",
I20151018-23:12:40.924(-6)?     "mongod": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongod"
I20151018-23:12:40.924(-6)?   }
I20151018-23:12:40.924(-6)? }
I20151018-23:12:40.924(-6)? ====================================
I20151018-23:12:41.076(-6)? INFO  electrify:plugins:  use  mongodb
I20151018-23:12:41.076(-6)? INFO  electrify:plugins:  use  nodejs
I20151018-23:12:41.076(-6)? MASTER: Requeued 0 jobs.
I20151018-23:12:41.076(-6)? INFO  electrify:scaffold:  ensuring basic structure
I20151018-23:12:41.076(-6)? INFO  electrify:app:  running app
I20151018-23:12:41.076(-6)? INFO  electrify:scaffold:  ensuring basic structure
I20151018-23:12:41.077(-6)? INFO  electrify:electron:  ensuring electron dependencies
I20151018-23:12:41.077(-6)? INFO  electrify:electron:  electron-prebuilt installation seems ok, moving on
I20151018-23:12:41.077(-6)? INFO  electrify:electron:  electron-packager installation seems ok, moving on
=> Started your app.

=> App running at: http://localhost:3000/
W20151018-23:12:41.368(-6)? (STDERR) npm WARN package.json @ No description
W20151018-23:12:41.368(-6)? (STDERR) npm WARN package.json @ No repository field.
W20151018-23:12:41.369(-6)? (STDERR) npm WARN package.json @ No README data
I20151018-23:12:41.793(-6)? INFO  electrify:index:  initializing
I20151018-23:12:41.794(-6)? ====================================
I20151018-23:12:41.795(-6)? {
I20151018-23:12:41.795(-6)?   "version": "1.4.0",
I20151018-23:12:41.795(-6)?   "is_development_mode": false,
I20151018-23:12:41.795(-6)?   "is_running_tests": false,
I20151018-23:12:41.796(-6)?   "stdio": "inherit",
I20151018-23:12:41.796(-6)?   "sys": {
I20151018-23:12:41.796(-6)?     "platform": "linux",
I20151018-23:12:41.796(-6)?     "arch": "x64",
I20151018-23:12:41.796(-6)?     "is_windows": false,
I20151018-23:12:41.796(-6)?     "is_linux": true,
I20151018-23:12:41.796(-6)?     "is_osx": false
I20151018-23:12:41.796(-6)?   },
I20151018-23:12:41.796(-6)?   "os": {
I20151018-23:12:41.796(-6)?     "name": "linux",
I20151018-23:12:41.796(-6)?     "home": "/home/suchipi",
I20151018-23:12:41.797(-6)?     "tmp": "/tmp"
I20151018-23:12:41.797(-6)?   },
I20151018-23:12:41.797(-6)?   "app": {
I20151018-23:12:41.797(-6)?     "root": "/home/suchipi/Code/nutti",
I20151018-23:12:41.797(-6)?     "is_packaged": false,
I20151018-23:12:41.797(-6)?     "electrify": "/home/suchipi/Code/nutti/.electrify",
I20151018-23:12:41.797(-6)?     "bin": "/home/suchipi/Code/nutti/.electrify/bin",
I20151018-23:12:41.797(-6)?     "dist": "/home/suchipi/Code/nutti/.electrify/.dist",
I20151018-23:12:41.797(-6)?     "settings": {}
I20151018-23:12:41.797(-6)?   },
I20151018-23:12:41.797(-6)?   "core": {
I20151018-23:12:41.798(-6)?     "tmp": "/tmp/electrify",
I20151018-23:12:41.798(-6)?     "root": "/tmp/electrify/core",
I20151018-23:12:41.798(-6)?     "node_mods": "/tmp/electrify/core/node_modules",
I20151018-23:12:41.798(-6)?     "electron": "/tmp/electrify/core/node_modules/electron-prebuilt/cli.js",
I20151018-23:12:41.798(-6)?     "packager": "/tmp/electrify/core/node_modules/electron-packager/cli.js"
I20151018-23:12:41.798(-6)?   },
I20151018-23:12:41.798(-6)?   "meteor": {
I20151018-23:12:41.798(-6)?     "root": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/meteor",
I20151018-23:12:41.798(-6)?     "tools": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/",
I20151018-23:12:41.798(-6)?     "dev_bundle": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle",
I20151018-23:12:41.798(-6)?     "server_lib": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/server-lib",
I20151018-23:12:41.799(-6)?     "server_modules": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules",
I20151018-23:12:41.799(-6)?     "node_mods": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/lib/node_modules",
I20151018-23:12:41.799(-6)?     "node": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/bin/node",
I20151018-23:12:41.799(-6)?     "npm": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/bin/npm-cli.js",
I20151018-23:12:41.799(-6)?     "mongo": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongo",
I20151018-23:12:41.799(-6)?     "mongod": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongod"
I20151018-23:12:41.799(-6)?   }
I20151018-23:12:41.799(-6)? }
I20151018-23:12:41.799(-6)? ====================================
I20151018-23:12:41.846(-6)? INFO  electrify:plugins:  acquire
I20151018-23:12:41.846(-6)? INFO  electrify:plugins:mongodb:  acquiring mongo
I20151018-23:12:41.846(-6)? INFO  electrify:plugins:nodejs:  acquiring nodejs
I20151018-23:12:41.847(-6)? INFO  electrify:plugins:  start
I20151018-23:12:41.847(-6)? INFO  electrify:plugins:mongodb:  app in development mode, skipping start
I20151018-23:12:41.847(-6)? INFO  electrify:plugins:nodejs:  app in development mode, skipping start
I20151018-23:12:41.850(-6)? INFO  electrify:app:  ensuring electrify dependencies
I20151018-23:12:41.851(-6)? INFO  electrify:plugins:  use  mongodb
I20151018-23:12:41.853(-6)? INFO  electrify:plugins:  use  nodejs
I20151018-23:12:41.898(-6)? PID 14725: Started 1 monq workers.
I20151018-23:12:41.900(-6)? INFO  electrify:scaffold:  ensuring basic structure
W20151018-23:12:42.239(-6)? (STDERR) npm WARN package.json my-electrified-app@ No description
W20151018-23:12:42.240(-6)? (STDERR) npm WARN package.json my-electrified-app@ No repository field.
W20151018-23:12:42.240(-6)? (STDERR) npm WARN package.json my-electrified-app@ No README data
W20151018-23:12:42.246(-6)? (STDERR) npm WARN package.json electrify@1.4.0 No repository field.
I20151018-23:12:42.272(-6)? INFO  electrify:electron:  launching electron
I20151018-23:12:42.477(-6)? INFO  electrify:index:  initializing
I20151018-23:12:42.481(-6)? ====================================
I20151018-23:12:42.482(-6)? {
I20151018-23:12:42.482(-6)?   "version": "1.4.0",
I20151018-23:12:42.482(-6)?   "is_development_mode": false,
I20151018-23:12:42.482(-6)?   "is_running_tests": false,
I20151018-23:12:42.482(-6)?   "stdio": "inherit",
I20151018-23:12:42.483(-6)?   "sys": {
I20151018-23:12:42.484(-6)?     "platform": "linux",
I20151018-23:12:42.484(-6)?     "arch": "x64",
I20151018-23:12:42.484(-6)?     "is_windows": false,
I20151018-23:12:42.484(-6)?     "is_linux": true,
I20151018-23:12:42.485(-6)?     "is_osx": false
I20151018-23:12:42.485(-6)?   },
I20151018-23:12:42.485(-6)?   "os": {
I20151018-23:12:42.485(-6)?     "name": "linux",
I20151018-23:12:42.485(-6)?     "home": "/home/suchipi",
I20151018-23:12:42.485(-6)?     "tmp": "/tmp"
I20151018-23:12:42.485(-6)?   },
I20151018-23:12:42.485(-6)?   "app": {
I20151018-23:12:42.485(-6)?     "root": "/home/suchipi/Code/nutti/.electrify",
I20151018-23:12:42.485(-6)?     "is_packaged": false,
I20151018-23:12:42.485(-6)?     "electrify": "/home/suchipi/Code/nutti/.electrify/.electrify",
I20151018-23:12:42.486(-6)?     "bin": "/home/suchipi/Code/nutti/.electrify/.electrify/bin",
I20151018-23:12:42.486(-6)?     "dist": "/home/suchipi/Code/nutti/.electrify/.electrify/.dist",
I20151018-23:12:42.486(-6)?     "settings": {}
I20151018-23:12:42.486(-6)?   },
I20151018-23:12:42.486(-6)?   "core": {
I20151018-23:12:42.486(-6)?     "tmp": "/tmp/electrify",
I20151018-23:12:42.486(-6)?     "root": "/tmp/electrify/core",
I20151018-23:12:42.486(-6)?     "node_mods": "/tmp/electrify/core/node_modules",
I20151018-23:12:42.486(-6)?     "electron": "/tmp/electrify/core/node_modules/electron-prebuilt/cli.js",
I20151018-23:12:42.486(-6)?     "packager": "/tmp/electrify/core/node_modules/electron-packager/cli.js"
I20151018-23:12:42.486(-6)?   },
I20151018-23:12:42.486(-6)?   "meteor": {
I20151018-23:12:42.487(-6)?     "root": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/meteor",
I20151018-23:12:42.487(-6)?     "tools": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/",
I20151018-23:12:42.487(-6)?     "dev_bundle": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle",
I20151018-23:12:42.487(-6)?     "server_lib": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/server-lib",
I20151018-23:12:42.487(-6)?     "server_modules": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules",
I20151018-23:12:42.487(-6)?     "node_mods": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/lib/node_modules",
I20151018-23:12:42.487(-6)?     "node": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/bin/node",
I20151018-23:12:42.487(-6)?     "npm": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/bin/npm-cli.js",
I20151018-23:12:42.487(-6)?     "mongo": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongo",
I20151018-23:12:42.487(-6)?     "mongod": "/home/suchipi/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongod"
I20151018-23:12:42.487(-6)?   }
I20151018-23:12:42.488(-6)? }
I20151018-23:12:42.488(-6)? ====================================
I20151018-23:12:42.561(-6)? INFO  electrify:plugins:  use  mongodb
I20151018-23:12:42.569(-6)? INFO  electrify:plugins:  use  nodejs
I20151018-23:12:42.742(-6)? INFO  electrify:index:  start
I20151018-23:12:42.744(-6)? INFO  electrify:plugins:  start
I20151018-23:12:42.744(-6)? INFO  electrify:plugins:mongodb:  app in development mode, skipping start
I20151018-23:12:42.745(-6)? INFO  electrify:plugins:nodejs:  app in development mode, skipping start
I20151018-23:15:38.947(-6)? INFO  electrify:app:  packaging app
I20151018-23:15:38.947(-6)? INFO  electrify:scaffold:  ensuring basic structure
I20151018-23:15:38.948(-6)? INFO  electrify:electron:  ensuring electron dependencies
I20151018-23:15:38.948(-6)? INFO  electrify:electron:  electron-prebuilt installation seems ok, moving on
I20151018-23:15:38.948(-6)? INFO  electrify:electron:  electron-packager installation seems ok, moving on
W20151018-23:15:39.336(-6)? (STDERR) npm WARN package.json @ No description
W20151018-23:15:39.336(-6)? (STDERR) npm WARN package.json @ No repository field.
W20151018-23:15:39.337(-6)? (STDERR) npm WARN package.json @ No README data
I20151018-23:15:39.798(-6)? INFO  electrify:plugins:  acquire
I20151018-23:15:39.798(-6)? INFO  electrify:plugins:mongodb:  acquiring mongo
I20151018-23:15:39.799(-6)? INFO  electrify:plugins:nodejs:  acquiring nodejs
I20151018-23:15:39.799(-6)? INFO  electrify:app:  ensuring electrify dependencies
W20151018-23:15:40.197(-6)? (STDERR) npm WARN package.json my-electrified-app@ No description
W20151018-23:15:40.197(-6)? (STDERR) npm WARN package.json my-electrified-app@ No repository field.
W20151018-23:15:40.198(-6)? (STDERR) npm WARN package.json my-electrified-app@ No README data
W20151018-23:15:40.203(-6)? (STDERR) npm WARN package.json electrify@1.4.0 No repository field.
I20151018-23:15:40.230(-6)? INFO  electrify:app:  bundling meteor
I20151018-23:16:12.945(-6)? shell.js: internal error
I20151018-23:16:12.950(-6)? Error: EXDEV, cross-device link not permitted '/tmp/electrify/bundling/bundle'
I20151018-23:16:12.950(-6)?     at Object.fs.renameSync (fs.js:555:18)
I20151018-23:16:12.950(-6)?     at /home/suchipi/.meteor/packages/arboleya_electrify/.1.4.0.1f367wx++os+web.browser+web.cordova/npm/node_modules/electrify/node_modules/shelljs/src/mv.js:77:8
I20151018-23:16:12.951(-6)?     at Array.forEach (native)
I20151018-23:16:12.951(-6)?     at Object._mv (/home/suchipi/.meteor/packages/arboleya_electrify/.1.4.0.1f367wx++os+web.browser+web.cordova/npm/node_modules/electrify/node_modules/shelljs/src/mv.js:53:11)
I20151018-23:16:12.951(-6)?     at Object.mv (/home/suchipi/.meteor/packages/arboleya_electrify/.1.4.0.1f367wx++os+web.browser+web.cordova/npm/node_modules/electrify/node_modules/shelljs/src/common.js:186:23)
I20151018-23:16:12.951(-6)?     at ChildProcess.<anonymous> (/home/suchipi/.meteor/packages/arboleya_electrify/.1.4.0.1f367wx++os+web.browser+web.cordova/npm/node_modules/electrify/lib/app.js:78:11)
I20151018-23:16:12.951(-6)?     at ChildProcess.emit (events.js:98:17)
I20151018-23:16:12.951(-6)?     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
I20151018-23:16:12.963(-6)? MASTER: Worker process killed.
```

**Comment by lacymorrow** [comment] 2015-10-19 05:56
I imagine this is a duplicate of #33.

**Comment by arboleya** [comment] 2015-11-03 18:32
@lacymorrow Duplicate of what?

@rIpteyed @suchipi Can you guys please update to last version (`2.0.0`) and let me know if it's working now?

**Comment by arboleya** [comment] 2015-11-13 13:46
@rIpteyed @suchipi Can I close this? Do you guys are still experiencing these problems?

**Comment by suchipi** [comment] 2015-11-14 20:06
Works with latest version (2.0.2), thanks. Sorry for the delay in response.

**Closed as completed** 2015-11-24 16:20 UTC
Labels: bug, unconfirmed
